[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#161616"
textColor = "#F5F5F5"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
